target("lanox2d")
    add_files("*.m")
    add_mflags("-Wno-error=deprecated-declarations")
    add_frameworks("UIKit", "OpenGLES", "QuartzCore")
    add_headerfiles("*.h")
    add_includedirs(".", {public = true})
