name: FreeBSD

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-12

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-FreeBSD
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1

      - name: Tests
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          mem: 4096
          copyback: false
          prepare: pkg install -y git curl unzip gmake llvm gsed bash perl5 openssl
          run: |
            git clone --recurse-submodules https://github.com/xmake-io/xmake.git /tmp/xmake -b dev
            cd /tmp/xmake
            gmake -j4
            gmake install
            export XMAKE_ROOT=y
            cd -
            xmake f -k ${{ matrix.kind }} -y -vD
            xmake -vD

