name: MingW (Msys2)

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
            { msystem: MINGW64, kind: static, arch: x86_64, prefix: /mingw64 },
            { msystem: MINGW64, kind: shared, arch: x86_64, prefix: /mingw64 },
            { msystem: MINGW32, kind: static, arch: i686,   prefix: /mingw32 },
            { msystem: MINGW32, kind: shared, arch: i686,   prefix: /mingw32 }
        ]

    steps:

      - uses: actions/checkout@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel unzip mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: Prepare
        shell: msys2 {0}
        run: |
          git clone https://github.com/xmake-io/xmake.git --recurse-submodules -b dev
          cd xmake
          make build
          make install PREFIX=${{ matrix.prefix }}
          xmake --version
          cd ..
          git reset --hard HEAD
          git clean -fdx

      - name: Tests
        shell: msys2 {0}
        run: |
          if [ "${{ matrix.arch }}" == "x86_64" ]; then
            xmake f -p mingw -a x86_64 -k ${{ matrix.kind }} -y -vD
            xmake -vD
          else
            xmake f -p mingw -a i386 -k ${{ matrix.kind }} -y -vD
            xmake -vD
          fi

