name: MingW (MacOS)

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-MingW_MacOS-${{ matrix.kind }}
        cancel-in-progress: true

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Prepare
        run: |
          brew install mingw-w64

      - name: Tests
        run: |
          xmake f -p mingw -k ${{ matrix.kind }} -y -vD
          xmake -vD

